import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import { TailwindIndicator } from "@/components/tailwind-indicator";

const merriWeather = Merriweather({
  variable: "--font",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Wordle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriWeather.variable} overflow-hidden antialiased`}>
        {children} <TailwindIndicator />
      </body>
    </html>
  );
}
